/*** -------------------------------------------- ***/
/*** This file has been auto-generated by the CLI ***/
/*** -------------------------------------------- ***/

export interface User {
    // Add members here...
}
